try:
    a = input("Введите первое число: ")
    b = input("Введите второе число: ")
    print("Результат: ", int(a)+int(b))
except ValueError:
    print("Результат:", str(a) + str(b))



















# from traceback import print_list

# def tryexcept(input):
#     try:
#         printlist.append(input)
#     except:
#         printlist.append('')
#     return print_list







# string1 = "4"
# string2 = "5"
# string3 = str(string1) + ", " + str(string2)
# try input()
# print(string3)


